from django.urls import path
from . import views

urlpatterns = [
    path('stats/', views.DashboardStatsView.as_view(), name='dashboard-stats'),
    path('annees/', views.AnneeListView.as_view(), name='annees'),
    path('annees/<int:pk>/', views.AnneeDetailView.as_view(), name='annee-detail'),
    path('cycles/', views.CycleListView.as_view(), name='cycles'),
    path('cycles/<int:pk>/', views.CycleDetailView.as_view(), name='cycle-detail'),
    path('parcours/', views.ParcoursListView.as_view(), name='parcours'),
    path('parcours/<int:pk>/', views.ParcoursDetailView.as_view(), name='parcours-detail'),
    path('specialites/', views.SpecialiteListView.as_view(), name='specialites'),
    path('specialites/<int:pk>/', views.SpecialiteDetailView.as_view(), name='specialite-detail'),
    path('paiements-scolarite/', views.PaiementScolariteListView.as_view(), name='paiements-scolarite'),
    path('paiements-scolarite/<int:pk>/', views.PaiementScolariteDetailView.as_view(), name='paiement-scolarite-detail'),
    path('semestres/', views.SemestreListView.as_view(), name='semestres'),
    path('semestres/<int:pk>/', views.SemestreDetailView.as_view(), name='semestre-detail'),
    path('niveaux/', views.NiveauListView.as_view(), name='niveaux'),
    path('niveaux/<int:pk>/', views.NiveauDetailView.as_view(), name='niveau-detail'),
    path('classes/', views.ClasseListView.as_view(), name='classes'),
    path('ues/', views.UEListView.as_view(), name='ues'),
    path('ues/<int:pk>/', views.UEDetailView.as_view(), name='ue-detail'),
    path('ecues/', views.ECUEListView.as_view(), name='ecues'),
    path('ecues/<int:pk>/', views.ECUEDetailView.as_view(), name='ecue-detail'),
    path('classes/<int:pk>/', views.ClasseDetailView.as_view(), name='classe-detail'),
    path('etudiants/', views.EtudiantListView.as_view(), name='etudiants'),
    path('etudiants/<int:pk>/', views.EtudiantDetailView.as_view(), name='etudiant-detail'),
    path('inscriptions/', views.InscriptionListView.as_view(), name='inscriptions'),
    path('inscriptions/create/', views.InscriptionCreateView.as_view(), name='inscription-create'),
    path('inscriptions/reinscription/', views.ReinscriptionView.as_view(), name='reinscription'),
    path('enseignants/', views.EnseignantListView.as_view(), name='enseignants'),
    path('enseignants/<int:pk>/', views.EnseignantDetailView.as_view(), name='enseignant-detail'),
]
