# Generated by Django 6.1 on 2026-08-29 20:27

import academic.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annees', to='accounts.etablissement')),
            ],
            options={
                'ordering': ['-libelle'],
                'unique_together': {('etablissement', 'libelle')},
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='accounts.etablissement')),
            ],
            options={
                'unique_together': {('etablissement', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.cycle')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='accounts.etablissement')),
            ],
            options={
                'ordering': ['libelle'],
                'unique_together': {('etablissement', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=academic.models.generate_code, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1)),
                ('date_nais', models.DateField(blank=True, null=True)),
                ('lieu_nais', models.CharField(blank=True, max_length=100)),
                ('nationalite', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tel', models.CharField(blank=True, max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='etudiants/')),
                ('bac', models.CharField(blank=True, choices=[('A', 'A'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F6', 'F6'), ('H', 'H'), ('R1', 'R1'), ('R5', 'R5'), ('R6', 'R6')], max_length=5)),
                ('moyenne_bac', models.FloatField(blank=True, null=True)),
                ('annee_bac', models.CharField(blank=True, max_length=4)),
                ('mention', models.CharField(blank=True, choices=[('Passable', 'Passable'), ('Assez-bien', 'Assez-bien'), ('Bien', 'Bien'), ('Très-bien', 'Très-bien')], max_length=20)),
                ('cycle', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('en cours', 'En cours'), ('admis', 'Admis'), ('refusé', 'Refusé'), ('inscrit', 'Inscrit')], default='en cours', max_length=20)),
                ('statut_paiement_inscription', models.BooleanField(default=False)),
                ('statut_paiement_concours', models.BooleanField(default=False)),
                ('etat', models.BooleanField(default=True)),
                ('date_candidature', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='accounts.etablissement')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='academic.specialite')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('niveau', models.CharField(max_length=20)),
                ('effectif', models.PositiveIntegerField(default=0)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='accounts.etablissement')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic.specialite')),
            ],
            options={
                'ordering': ['niveau', 'libelle'],
                'unique_together': {('etablissement', 'libelle')},
            },
        ),
        migrations.CreateModel(
            name='TypeDiplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_diplome', to='accounts.etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=200)),
                ('semestre', models.CharField(max_length=10)),
                ('niveau', models.CharField(max_length=20)),
                ('credits', models.PositiveSmallIntegerField(default=0)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='accounts.etablissement')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='academic.specialite')),
            ],
            options={
                'ordering': ['semestre', 'code'],
                'unique_together': {('etablissement', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_inscription', models.CharField(choices=[('nouveau', 'Nouveau'), ('reinscrit', 'Réinscrit'), ('transfert', 'Transfert')], default='nouveau', max_length=20)),
                ('statut_paiement', models.BooleanField(default=False)),
                ('montant_paye', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('est_valide', models.BooleanField(default=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academic.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academic.classe')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='accounts.etablissement')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academic.etudiant')),
            ],
            options={
                'ordering': ['-date_inscription'],
                'unique_together': {('etudiant', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='ECUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=200)),
                ('credits', models.PositiveSmallIntegerField(default=0)),
                ('coefficient', models.FloatField(default=1)),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecues', to='academic.ue')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('ue', 'code')},
            },
        ),
    ]
