# Generated by Django 6.1 on 2026-08-30 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('accounts', '0002_abonnement_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='accounts.etablissement')),
            ],
            options={
                'ordering': ['libelle'],
                'unique_together': {('etablissement', 'code')},
            },
        ),
        migrations.AddField(
            model_name='specialite',
            name='parcours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.parcours'),
        ),
    ]
