# Generated by Django 6.1 on 2026-08-30 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_add_parcours'),
        ('accounts', '0002_abonnement_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=100)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='accounts.etablissement')),
            ],
            options={
                'ordering': ['ordre', 'code'],
                'unique_together': {('etablissement', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=100)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='accounts.etablissement')),
            ],
            options={
                'ordering': ['ordre', 'code'],
                'unique_together': {('etablissement', 'code')},
            },
        ),
    ]
