# Generated by Django 6.1 on 2026-08-30 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_add_semestre_niveau'),
        ('accounts', '0002_abonnement_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=10)),
                ('montant_du', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('partiel', 'Partiel'), ('attente', 'En attente')], default='attente', max_length=20)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_scolarite', to='academic.anneeacademique')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_scolarite', to='accounts.etablissement')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_scolarite', to='academic.etudiant')),
            ],
            options={
                'ordering': ['-periode'],
                'unique_together': {('etudiant', 'annee', 'periode')},
            },
        ),
    ]
