# Generated by Django 6.1 on 2026-08-30 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_add_paiement_scolarite'),
        ('accounts', '0002_abonnement_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tel', models.CharField(blank=True, max_length=30)),
                ('grade', models.CharField(choices=[('professeur', 'Professeur Titulaire'), ('mcf', 'Maître de Conférences'), ('assistant', 'Assistant'), ('vacataire', 'Vacataire'), ('charge_cours', 'Chargé de Cours'), ('autre', 'Autre')], default='assistant', max_length=20)),
                ('etat', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignants', to='accounts.etablissement')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants', to='academic.specialite')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
